### ISSUE TITLE
TODO / Architecture

### ISSUE THREAD

**Issue by Nicofuma** [ptitlazy/sys-rep#1]
# Archi

Les wokers recoivent une tache a exécuter. Ils recupère via scp les dépendances de celle-ci via scp sur la master. Puis ils copie le fichier cible sur le master et renvoie via mpi un message de "tache accomplie"

Le master a
- un vector de taches disponibles
- un vector de workers idle (vide au debut?)
## Algo Master

MPI_Init

boucle (i)
- Le master attend un message de la part d'un worker (signifiant qu'il a fini une tache et donc qu'il est prêt à en effectuer une autre)
- Il met à jour son vector de tâches disponible
- si il y a des taches dispo
  - Il envoie une tâche au worker qui s'est signalé au debut de boucle
  - Puis tant qu'"il y a des tâches et des workers dans le vector de idle, il envoie une tâche à chaque workers idle
- sinon
  - le master ajoute le worker courant dans le vector des idle
- test si il reste des tâche non réalisées
  - si oui, on reboucle (i)
  - si non, on sort de la boucle et on signal par message mpi à tous les workers que c'est fini

fin boucle (i)
MPI_Finalize()
exit
## Algo worker

Le worker récupère dans l'ordre:
- le nom de la cible
- la commande
- le nombre de dépendances (int)
- les dépendances
# TODO
- [x] Master : Initialiser un vecteur de tâche avec l'ensemble des feuilles
- [ ] Master : Envoyer une tâche du vecteur de tâche à un worker
- [ ] Worker : Récupérer les dépendances
- [ ] Worker : exécuter une tache et envoyé le nouveau fichier
- [ ] Master : Tester si les tâches parentes d'une tâche sont prêtes à être exécutées
- [ ] Master : Modifier le vecteur de tâche prête.
- [ ] Master : Tester si on a tout fait (règle racine effectuée --> facile avec noeud ROOT)
- [ ] Master : conserver un vector de workers idle
- [ ] Master : signaler aux workers que tout est fini
- [ ] W / M : gérer le cas où une exécution ne se passe pas bien (tout arrêter proprement)

**Comment by ptitlazy** [comment]
Les wokers recoivent une tache a exécuter. Ils recupère via scp les dépendances de celle-ci via scp sur la master. Puis ils copie le fichier cible sur le master et renvoie via mpi un message de "tache accomplie"

Le master a 
- un vector de taches disponibles
- un vector de workers idle (vide au debut?)

**Comment by ptitlazy** [comment]
Algo Master

MPI_Init

boucle (i)
- Le master attend un message de la part d'un worker (signifiant qu'il a fini une tache et donc qu'il est prêt à en effectuer une autre)
- Il met à jour son vector de tâches disponible

- si il y a des taches dispo
    - Il envoie une tâche au worker qui s'est signalé au debut de boucle
    - Puis tant qu'"il y a des tâches et des workers dans le vector de idle, il envoie une tâche à chaque workers idle

- sinon
    - le master ajoute le worker courant dans le vector des idle

- test si il reste des tâche non réalisées
    - si oui, on reboucle (i)
    - si non, on sort de la boucle et on signal par message mpi à tous les workers que c'est fini
fin boucle (i)

MPI_Finalize()
exit
